baseURL = 'https://phuocchubeo123.github.io/'
languageCode = 'en-us'
title = 'Pham Van Long Phuoc'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"